
WITH CTE AS(
    SELECT 
    TO_TIMESTAMP(STARTED_AT) AS DATE_TIMESTAMP,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS START_DATE,
    month(TO_TIMESTAMP(STARTED_AT)) AS START_MONTH,

    CASE WHEN DAYNAME(TO_TIMESTAMP(START_DATE)) IN ('SAT', 'SUN')
    THEN 'WEEKEND'
    ELSE 'BUSINESS DAY'
    end AS START_DAY,

    {{get_season('STARTED_AT')}} AS START_SEASON

    FROM 
    {{ source('demo', 'bike') }}
    WHERE STARTED_AT != 'started_at'  
)

SELECT * FROM CTE